controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

not_found:
    path: /{catchall}
    controller: App\Controller\MainController::notFound
    requirements:
        catchall: ".+"